# 2.预备知识

## 2.1 数据操作

### 2.1.1入门

In [1]:
import torch

张量（tensor）   
一个轴的张量：向量（vector）   
两个轴的张量：矩阵（matrix）    
两轴以上张量没有特殊名称


In [2]:
x = torch.arange(12)
x
# arange表示创建一个行向量，（12）表示包含0开始的12个整数
# 默认创建为整数
# 张量中每个值称为张量的元素（element）

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape #访问张量的形状（沿每个轴的长度）

torch.Size([12])

In [4]:
# 若只想知道元素总数，则形状所有元素相乘，可检查大小（size）
x.numel()

12

In [5]:
# 若想改变一个张量的形状而不改变元素数量和元素值 - reshape函数
# eg把一个（12，）的行向量转化为形状为（3，4）的矩阵
X = x.reshape(3, 4) #顺序为行 - 列 
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
# 不用手动指定每个维度来改变形状 - 可用-1自动计算出维度
# 例如想要一个3行的，不用手动计算出需要12/3=4列，可用-1代替，自动计算
X = x.reshape(3, -1)
X
# 同理x.reshape(-1, 4).......

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
# 有时候我们需要全为0 or 1 or 随机 的张量
torch.zeros((2,3,4)) #全0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones(2,3,4) #全1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn(3,4) #randn - 其中每个元素服从均值为0，标准差为1的标准正态分布

tensor([[ 1.7879, -0.2418,  0.0962, -1.2162],
        [ 0.0487,  0.7488, -0.1190, -1.2761],
        [ 0.4164,  0.4404,  0.6731,  0.2135]])

In [10]:
# 也可以通过提供列表，为所需张量的每个元素赋予确定值
# 最外层的列表（行）对应于轴0(张量的第一个维度)，内层的列表（列）对应于轴1（张量第二个维度）
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2运算符

In [11]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
torch.exp(x) #求幂运算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [13]:
X = torch.arange(12,dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)
# dim = 0 行拼接 ；dim = 1 列拼接 cat - 拼接张量

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [14]:
#逻辑运算符 - == 判断两个张量对于未知是否相等，相等的项值为1为真 
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
# 张量求和 -- 产生一个新的单元素张量(注意 是单元素张量)
X.sum()

tensor(66.)

### 2.1.3广播机制

上面的部分都是通过对相同形状的张量进行操作
广播机制(broadcasting mechanism)：    
1.通过适当复制元素扩展一个or两个数组，转化之后两个张量有相同的形状   
2.对生成的数组执行案按元素操作

In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
# 广播机制将两个张量都扩展为更大的3X2矩阵 a复制列，b复制行
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.3索引和切片

In [18]:
# 与python中一样，张量中的元素可以通过索引访问（第一个索引0，最后一个索引-1）
# [-1]选择最后一个元素 [1:3]选择第二个和第三个元素
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [19]:
X[1,2] = 9 #注意不是1行2列，索引顺序要+1 -- 2行3列
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
X[0:2,:] = 12 #按轴0、轴1的顺序，中间用，连接（：表示沿此轴所有元素）
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.5节省内存

In [21]:
# 这里的id（）函数可以提供内存中引用对象的确切位置
before = id(Y)
Y = Y+X
id(Y) == before #说明Y的内存位置发生了变化，结果分配了新的内存
# 不可取 1.新结果分贝内存，某些情况如机器学习，参数太多 - 内存占用太大
# 2.不原地更新的话其他引用会指向旧的内存位置，可能会引用的旧的参数

False

In [22]:
# 执行原地操作 -- 利用切片表示法将操作结果分配给先前分配的数组
# 创建一个新的矩阵Z，形状与另一个Y相同，使用zeros_like来分配一个全0的块
Z = torch.zeros_like(Y)
print("id(Z):",id(Z))
Z[:]=X+Y
print("id(Z):",id(Z))

id(Z): 1752304917856
id(Z): 1752304917856


In [23]:
# 后续计算没有重复使用X，也可以使用X[:] = X + Y或者X += Y来减少操作的内存开销。
before = id(X)
X += Y
id(X) == before 

True

### 2.1.6转换为其他python对象

In [24]:
# 将深度学习框架定义的张量转化为Numpy张量(ndarray)，以及反之
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
# 将大小为1的张量转化为Python标量，可以通过item函数
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2.1.7小结

深度学习存储和操作数据的主要接口是张量（n维数组）

### 2.1.8练习

In [26]:
# 运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。
X = torch.arange(12,dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [27]:
X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [28]:
# 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？
a = torch.zeros(9).reshape((3,3,1))
b = torch.arange(8).reshape((1, 2,4))
a,b
# 注意 广播机制要求两个张量对应维度满足以下条件之一：
# 1. 维度相同
# 2. 其中一个维度为1
# 3. 其中一个维度不存在

(tensor([[[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]]]),
 tensor([[[0, 1, 2, 3],
          [4, 5, 6, 7]]]))

In [29]:
#a+b 输出会报错
#修改为：
a = torch.zeros(9).reshape((3,3,1))
b = torch.arange(4).reshape((1, 1,4))
a,b

(tensor([[[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]]]),
 tensor([[[0, 1, 2, 3]]]))

In [30]:
a+b #成功广播

tensor([[[0., 1., 2., 3.],
         [0., 1., 2., 3.],
         [0., 1., 2., 3.]],

        [[0., 1., 2., 3.],
         [0., 1., 2., 3.],
         [0., 1., 2., 3.]],

        [[0., 1., 2., 3.],
         [0., 1., 2., 3.],
         [0., 1., 2., 3.]]])

## 2.2数据预处理

### 2.2.1读取数据集

In [31]:
#创建数据集
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [32]:
#安装pandas
!pip install pandas

In [33]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
