# 2.预备知识

## 2.1 数据操作

### 2.1.1入门

In [62]:
import torch

张量（tensor）   
一个轴的张量：向量（vector）   
两个轴的张量：矩阵（matrix）    
两轴以上张量没有特殊名称


In [63]:
x = torch.arange(12)
x
# arange表示创建一个行向量，（12）表示包含0开始的12个整数
# 默认创建为整数
# 张量中每个值称为张量的元素（element）

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
x.shape #访问张量的形状（沿每个轴的长度）

torch.Size([12])

In [65]:
# 若只想知道元素总数，则形状所有元素相乘，可检查大小（size）
x.numel()

12

In [66]:
# 若想改变一个张量的形状而不改变元素数量和元素值 - reshape函数
# eg把一个（12，）的行向量转化为形状为（3，4）的矩阵
X = x.reshape(3, 4) #顺序为行 - 列 
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [67]:
# 不用手动指定每个维度来改变形状 - 可用-1自动计算出维度
# 例如想要一个3行的，不用手动计算出需要12/3=4列，可用-1代替，自动计算
X = x.reshape(3, -1)
X
# 同理x.reshape(-1, 4).......

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [68]:
# 有时候我们需要全为0 or 1 or 随机 的张量
torch.zeros((2,3,4)) #全0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [69]:
torch.ones(2,3,4) #全1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [70]:
torch.randn(3,4) #randn - 其中每个元素服从均值为0，标准差为1的标准正态分布

tensor([[ 1.5418, -0.3594, -0.6713, -0.4202],
        [-0.8342,  1.0379,  0.3760, -0.9888],
        [ 0.1474,  0.3125,  0.8539, -0.8015]])

In [71]:
# 也可以通过提供列表，为所需张量的每个元素赋予确定值
# 最外层的列表（行）对应于轴0(张量的第一个维度)，内层的列表（列）对应于轴1（张量第二个维度）
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2运算符

In [72]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [73]:
torch.exp(x) #求幂运算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [74]:
X = torch.arange(12,dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)
# dim = 0 行拼接 ；dim = 1 列拼接 cat - 拼接张量

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [75]:
#逻辑运算符 - == 判断两个张量对于未知是否相等，相等的项值为1为真 
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [76]:
# 张量求和 -- 产生一个新的单元素张量(注意 是单元素张量)
X.sum()

tensor(66.)

### 2.1.3广播机制

上面的部分都是通过对相同形状的张量进行操作
广播机制(broadcasting mechanism)：    
1.通过适当复制元素扩展一个or两个数组，转化之后两个张量有相同的形状   
2.对生成的数组执行案按元素操作

In [77]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [78]:
# 广播机制将两个张量都扩展为更大的3X2矩阵 a复制列，b复制行
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.3索引和切片

In [79]:
# 与python中一样，张量中的元素可以通过索引访问（第一个索引0，最后一个索引-1）
# [-1]选择最后一个元素 [1:3]选择第二个和第三个元素
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [80]:
X[1,2] = 9 #注意不是1行2列，索引顺序要+1 -- 2行3列
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [81]:
X[0:2,:] = 12 #按轴0、轴1的顺序，中间用，连接（：表示沿此轴所有元素）
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.5节省内存

In [82]:
# 这里的id（）函数可以提供内存中引用对象的确切位置
before = id(Y)
Y = Y+X
id(Y) == before #说明Y的内存位置发生了变化，结果分配了新的内存
# 不可取 1.新结果分贝内存，某些情况如机器学习，参数太多 - 内存占用太大
# 2.不原地更新的话其他引用会指向旧的内存位置，可能会引用的旧的参数

False

In [83]:
# 执行原地操作 -- 利用切片表示法将操作结果分配给先前分配的数组
# 创建一个新的矩阵Z，形状与另一个Y相同，使用zeros_like来分配一个全0的块
Z = torch.zeros_like(Y)
print("id(Z):",id(Z))
Z[:]=X+Y
print("id(Z):",id(Z))

id(Z): 2222464426688
id(Z): 2222464426688


In [84]:
# 后续计算没有重复使用X，也可以使用X[:] = X + Y或者X += Y来减少操作的内存开销。
before = id(X)
X += Y
id(X) == before 

True

### 2.1.6转换为其他python对象

In [85]:
# 将深度学习框架定义的张量转化为Numpy张量(ndarray)，以及反之
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [86]:
# 将大小为1的张量转化为Python标量，可以通过item函数
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2.1.7小结

深度学习存储和操作数据的主要接口是张量（n维数组）

### 2.1.8练习

In [87]:
# 运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。
X = torch.arange(12,dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [88]:
X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [89]:
# 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？
a = torch.zeros(9).reshape((3,3,1))
b = torch.arange(8).reshape((1, 2,4))
a,b
# 注意 广播机制要求两个张量对应维度满足以下条件之一：
# 1. 维度相同
# 2. 其中一个维度为1
# 3. 其中一个维度不存在

(tensor([[[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]]]),
 tensor([[[0, 1, 2, 3],
          [4, 5, 6, 7]]]))

In [90]:
#a+b 输出会报错
#修改为：
a = torch.zeros(9).reshape((3,3,1))
b = torch.arange(4).reshape((1, 1,4))
a,b

(tensor([[[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]]]),
 tensor([[[0, 1, 2, 3]]]))

In [91]:
a+b #成功广播

tensor([[[0., 1., 2., 3.],
         [0., 1., 2., 3.],
         [0., 1., 2., 3.]],

        [[0., 1., 2., 3.],
         [0., 1., 2., 3.],
         [0., 1., 2., 3.]],

        [[0., 1., 2., 3.],
         [0., 1., 2., 3.],
         [0., 1., 2., 3.]]])

## 2.2数据预处理

### 2.2.1读取数据集

In [92]:
#创建数据集
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [93]:
#安装pandas
!pip install pandas

In [94]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


### 2.2.2 处理缺失值

数据中 NAN 表示缺失值 - 可以用插值法（一个替代值弥补缺失值）、删除法（直接忽略）进行处理

In [95]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# 位置索引iloc，前两列选出作为输入特征，第3列作为输出特征，赋值给inputs和outputs变量
inputs = inputs.fillna(inputs.mean(numeric_only=True))
# .fillna()方法，使用均值填充NA值   .mean()方法，计算均值 
print(inputs)


   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [96]:
inputs = pd.get_dummies(inputs, dummy_na=True)
# pandas 提供的独特编码方式，把离散值转化为机器学习可以处理的数值形式
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


### 2.2.3 转换为张量格式

In [97]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## 2.3 线性代数

### 2.3.1 标量


In [98]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y , x*y , x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

### 2.3.2 向量

一维张量表示向量

In [99]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [100]:
x[2]
# 通过索引访问张量中的任意元素

tensor(2)

#### 2.3.2.1 长度、维度和形状

In [101]:
len(x)
# 访问张量的长度

4

In [102]:
x.shape
# 张量只有一个轴时候 - 也可以用.shape访问向量长度
# shape - 访问向量的长度，输出一个元素组

torch.Size([4])

注：向量or轴的维度一般表示向量or轴的长度，即元素数量。张量的维度表示张量的轴数

### 2.3.3 矩阵

In [103]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [104]:
A.T
# 访问A的转置矩阵

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [105]:
# 对称矩阵
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 2.3.4 张量

In [106]:
# 向量 - 一维张量 ； 矩阵 - 二维张量
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5 张量算法的基本性质


In [107]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [108]:
A*B #Hadamard积，哈达玛积，对应位置相乘

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [109]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape
# 张量乘以or加上标量不改变标量形状，每个元素为其与标量的乘积或和

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 2.3.6 降维

In [110]:
x =  torch.arange(4,dtype=torch.float32)
x,x.sum() #.sum()求和运算,变为一个标量

(tensor([0., 1., 2., 3.]), tensor(6.))

In [111]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [112]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape
# 汇总所有行的元素来降维（轴0）

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [113]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [114]:
A.sum(axis=[0, 1])  # 结果和A.sum()相同

tensor(190.)

In [115]:
# 求平均值的两种方法
A.mean(),A.sum()/A.numel() #总和除以个数

(tensor(9.5000), tensor(9.5000))

In [116]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]
# 指定轴降低张量的维度

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

#### 2.3.6.1 非降维求和

In [117]:
sum_A = A.sum(axis=1,keepdims=True) #没有后面参数则会降维为向量
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [118]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [119]:
A.cumsum(axis=0) #按行累计求和（n行等于前n-1行之和）

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

### 2.3.7点积（Dot product）

In [ ]:
y = torch.ones(4,dtype = torch.float32)
x,y,torch.dot(x,y) #向量的点积 - 相同位置的乘积
# 常用于加权平均

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [121]:
torch.sum(x*y)

tensor(6.)

### 2.3.8 矩阵-向量积

In [ ]:
A.shape,x.shape,torch.mv(A,x)
# 矩阵-向量积(matrix-vector product)
# 可看做n维向量向m维向量的转化 （A:mxn）

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

### 2.3.9 矩阵-矩阵乘法

In [ ]:
B = torch.ones(4,3)
A,B,torch.mm(A,B),A @ B
# 矩阵乘法torch.mm(A,B)和A @ B等价

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

### 2.3.10 范数

线性代数中，范数是将向量映射到标量的函数f，满足以下性质：
1. 非负性：对于任意非零向量x，有f(x) ≥ 0。
2. 齐次性：对于任意常数α和向量x，有f(αx) = |α|f(x)。
3. 三角不等式：对于任意向量x和y，有f(x + y) ≤ f(x) + f(y)。
范数最小为0，当且仅当向量为0向量。
常见的范数包括：
1. L1范数：也称为曼哈顿范数，定义为向量x中所有元素的绝对值的和。
2. L2范数：也称为欧几里得范数，定义为向量x的欧几里得长度。

In [ ]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)  # L2范数

tensor(5.)

In [ ]:
torch.abs(u).sum() # L1范数（abs为求绝对值）

tensor([3., 4.])

L1范数和L2范数都是Lp范数的特例，Lp范数为：
$$
\|x\|_p = \left(\sum_{i=1}^n |x_i|^p\right)^{\frac{1}{p}}
$$

类似于向量L2范数，X的Frobenius范数定义为：
$$
||X||_F=\sqrt{\sum_{i=1}^m\sum_{j=1}^n|x_{ij}|^2}
$$

In [132]:
torch.ones((4,9)),torch.norm(torch.ones((4,9)))

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))

### 2.3.10.1 范数的目标   
解决一些优化问题。 一般来说目标都被表达为范数

### 2.3.13 练习

In [ ]:
# 本节中定义了形状（2,3,4）的张量X。len(X)的输出结果是什么？
X = torch.arange(24).reshape(2, 3, 4)
len(X) #输出的结果为轴0的长度，即2。

2

In [151]:
# 运行A/A.sum(axis=1)，看看会发生什么。请分析一下原因？
print(A)
print(A.sum(axis=1))
# 运行A/A.sum(axis=1)会报错，因为A.sum(axis=1)的结果是一个列向量，而A是一个矩阵，它们的形状不匹配。
# 反之，如果A/A.sum(axis=0)则是正确的
A/A.sum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([ 6., 22., 38., 54., 70.])


tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

In [158]:
# 考虑一个具有形状(2,3,4)的张量，在轴0、1、2上的求和输出是什么形状?
print(X)
X.sum(axis=0).shape,X.sum(axis=1).shape,X.sum(axis=2).shape
# 如果添加参数keepdims=True，对应求和结果会保持相同的维度，即(1,3,4)...


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

In [ ]:
# 为linalg.norm函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?
print(X)
torch.linalg.norm(X.float())
# 注意：torch.linalg.norm() 函数只能用于浮点数类型的张量，因此需要将 X 转换为浮点数类型。
# linalg.norm函数作用：计算整个张量的弗罗贝尼乌斯范数（所有元素平方和开根，标量）。

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


tensor(65.7571)